### ISSUE TITLE
New plugin: SQL Server

### ISSUE THREAD

**Issue by mikoskinen** [weikio/ApiFramework#6]
Plugin which offers the same functionality as the ODBC-plugin but uses the SQLClient.

This should be done in new repository: ApiFramework.Plugins.SqlServer. Use weikio/Template
as the starting point.

### Configuration: 
* Same as ODBC (connection string and commands)

### Implementation:
* Create ApiFactory which 1. uses the schema to create DTOs and 2. uses the DTOs to create the required data access classes.

**Note**: The ODBC plugin generates all the data access classes line by line. We don't want that in this one. Instead create an abstract base class which can do all the operations with the DB and then for each DTO, inherit the base class and set the required properties etc. 

For example, see the ApiFramework.Plugins.SharePoint.

**Comment by percramer** [comment]
HI,

I like that the endpoints are created dynamically. But for SQL Server only GET endpoints are created? Is there a special reason for that? The OpenAPI plugin does allow for PUT / POST commands I noticed.
